//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caisse
{
    using System;
    using System.Collections.Generic;
    
    public partial class partie
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datePartie { get; set; }
        public Nullable<int> nbrStrikes { get; set; }
        public Nullable<int> nbrSpares { get; set; }
        public Nullable<int> nbrRigole { get; set; }
        public Nullable<int> nbrPoints { get; set; }
        public int joueur_id { get; set; }
        public Nullable<int> numPiste { get; set; }
    
        public virtual joueur joueur { get; set; }
    }
}
